### ISSUE TITLE
Access to JSOC2

### ISSUE THREAD

**Issue by Rankicker795** [sunpy/drms#18]
Would it be possible to configure access to JSOC2 using an user name and password?

**Comment by kbg** [comment]
I think it should be easy to add another server config for JSOC2 to the `drms` module, which should work fine from within the JSOC/Stanford network.

But right now I'm not sure how they do the user/password authentication, and how much work it would be to integrate this into the `drms` Python module. I will need to ask somebody from the DRMS/JSOC development team about it.

**Comment by kbg** [comment]
I had a discussion with one of the JSOC developers from Stanford, and he told me that they want to move people away from `jsoc2`. According to him the password access to `jsoc2` was some kind of hack, and it looks like they want to remove it in the future.

Do you need access to some specific series that are only available from `jsoc2`? In this case, you can probably just ask them to make these series available on the `jsoc` server.

**Comment by kbg** [comment]
I'm closing this for now. Feel free to reopen if it is still relevant.
