### ISSUE TITLE
Add citation recommendation

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/drms#22]
Currently, the docs do not provide any information on how to cite the drms package. 

As suggested by @mbobra, the easiest way to resolve this is probably to create a Zenodo record for the latest release of the package and just recommend that people cite that DOI when using drms in publications.

**Comment by mbobra** [comment]
I agree with @wtbarnes ! [Here](https://guides.github.com/activities/citable-code/) is the Github guide on making code citeable using Zenodo.

**Comment by kbg** [comment]
I forgot to close this issue. The release-independent DOI for the drms package is [10.5281/zenodo.2572849](https://doi.org/10.5281/zenodo.2572849).

**Comment by kbg** [comment]
I added a DOI badge to the README file (commit: 1a9592361cfdb061a75bc5224e039bd9b0270b02). Feel free to reopen this issue if you think that we should add more text about citing this package.

**Comment by wtbarnes** [comment]
Thanks! We should have a paper coming out in the next few months or so which cites drms.

**Comment by wtbarnes** [comment]
I'm reopening this as there's still not clear guidance in either the README or the docs about how to cite `drms`. Now that it is on Zenodo and there's a JOSS paper, there should probably be a blurb somewhere that says to cite the JOSS paper as well as the Zenodo DOI for the specific version used.

It may be a good idea to include a CITATION.rst file as well, similar to the one we have in sunpy core.
