### ISSUE TITLE
[0.5.6] Config error in pytest

### ISSUE THREAD

**Issue by olebole** [sunpy/drms#24]
While trying to package 0.5.6 for Debian, I observed an error in the build time test:
```
============================= test session starts ==============================
platform linux -- Python 3.7.2+, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
rootdir: /build/drms-0.5.6, inifile:
collected 0 items / 1 errors

==================================== ERRORS ====================================
______________________________ ERROR collecting  _______________________________
/usr/lib/python3/dist-packages/_pytest/config/__init__.py:953: in getoption
    val = getattr(self.option, name)
E   AttributeError: 'Namespace' object has no attribute 'run_jsoc'

During handling of the above exception, another exception occurred:
/usr/lib/python3/dist-packages/pluggy/hooks.py:284: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:67: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3/dist-packages/pluggy/manager.py:61: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
drms/tests/conftest.py:45: in pytest_ignore_collect
    if not config.getoption('run_jsoc'):
/usr/lib/python3/dist-packages/_pytest/config/__init__.py:964: in getoption
    raise ValueError("no option named %r" % (name,))
E   ValueError: no option named 'run_jsoc'
```
Although I don't see a relevant change, it is a regression. In an identical environment, this does not happen with 0.5.5.

**Comment by kbg** [comment]
Hi @olebole,

I could not reproduce your problem when I used the same package versions in a
fresh virtual environment:

    $ python3 -m venv gh24-env
    $ source gh24-env/bin/activate
    $ pip install -U pip
    $ pip install drms==0.5.6 pytest==3.10.1 py==1.7.0 pluggy==0.8.0

    $ python -m drms.tests
    running: pytest /home/kolja/work/drms-issues/gh24/gh24-env/lib/python3.7/site-packages/drms
    =================================== test session starts ====================================
    platform linux -- Python 3.7.2, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
    rootdir: /home/kolja/work/drms-issues/gh24, inifile:
    collected 78 items

    gh24-env/lib/python3.7/site-packages/drms/tests/test_client.py ........              [ 10%]
    gh24-env/lib/python3.7/site-packages/drms/tests/test_config.py ...................   [ 34%]
    gh24-env/lib/python3.7/site-packages/drms/tests/test_exceptions.py ....              [ 39%]
    gh24-env/lib/python3.7/site-packages/drms/tests/test_init.py ..........              [ 52%]
    gh24-env/lib/python3.7/site-packages/drms/tests/test_to_datetime.py ................ [ 73%]
    sss...                                                                               [ 80%]
    gh24-env/lib/python3.7/site-packages/drms/tests/test_utils.py ...............        [100%]

    =========================== 75 passed, 3 skipped in 0.15 seconds ===========================

    $ python -m drms.tests --run-jsoc
    running: pytest --run-jsoc /home/kolja/work/drms-issues/gh24/gh24-env/lib/python3.7/site-pac
    kages/drms
    =================================== test session starts ====================================
    platform linux -- Python 3.7.2, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
    rootdir: /home/kolja/work/drms-issues/gh24, inifile:
    collected 100 items
    [...]
    ========================== 92 passed, 8 skipped in 15.20 seconds ===========================

It also works as expected, when I run the tests directly from the source tree
of the PyPI package:

    $ pip uninstall drms

    $ pip download --no-deps drms==0.5.6 -d src-pip/
    $ tar -xzf src-pip/drms-0.5.6.tar.gz -C src-pip/
    $ pytest src-pip/drms-0.5.6/drms
    =================================== test session starts ====================================
    platform linux -- Python 3.7.2, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
    rootdir: /home/kolja/work/drms-issues/gh24/src-pip/drms-0.5.6, inifile:
    collected 78 items
    [...]
    =========================== 75 passed, 3 skipped in 0.36 seconds ===========================

and the same for the GitHub release sources:

    $ wget https://github.com/sunpy/drms/archive/v0.5.6.tar.gz -P src-gh/
    $ tar -xzf src-gh/v0.5.6.tar.gz -C src-gh/
    $ pytest src-gh/drms-0.5.6/drms
    =================================== test session starts ====================================
    platform linux -- Python 3.7.2, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
    rootdir: /home/kolja/work/drms-issues/gh24/src-gh/drms-0.5.6, inifile:
    collected 78 items
    [...]
    =========================== 75 passed, 3 skipped in 0.36 seconds ===========================

Could you try if it works on your system, when you install and run it like I did above?

**Comment by kbg** [comment]
I think I found the problem: If you run the tests using the `pytest` command, you need to specify the `drms` module directory, not the package directory. For instance

    pytest src-gh/drms-0.5.6/drms

instead of

    pytest src-gh/drms-0.5.6

When I run the latter command, I get the same kind of error that you had.

**Comment by kbg** [comment]
This issue seems to be resolved. Feel free to reopen it, if there are still any related problems.
