### ISSUE TITLE
Add support for processing such as cutouts

### ISSUE THREAD

**Issue by Cadair** [sunpy/drms#25]
This would allow people to use the cutout service etc.

See [this conversation](https://matrix.to/#/!HZAyHIffAnrJIWEjtH:matrix.org/$15156044671100488iXtVD:matrix.org?via=matrix.org&via=cadair.com) in matrix for some context.

**Comment by wtbarnes** [comment]
See also sunpy/sunpy#1259. I suspect this will require some conversations with the DRMS/JSOC folks.

**Comment by wtbarnes** [comment]
Here's an example of a DRMS HTTP query to the JSOC for a cutout,

```
https://jsoc.stanford.edu/cgi-bin/ajax/jsoc_fetch?op=exp_request&ds=aia.lev1_euv_12s[2015.10.17_04:33:30/300m@84s][171,193,94,304]{image}&sizeratio=1&process=n=0|im_patch,t_start=2015-10-17T04:33:30.000,t_stop=2015-10-17T09:33:30.000,t=0,r=0,c=0,cadence=84s,locunits=arcsec,boxunits=arcsec,t_ref=2015-10-17T04:33:30.000,x=-517.2,y=-246,width=345.6,height=345.6&requestor=FirstLast&notify=first.last@email.com&method=url-tar&filenamefmt=aia.lev1_euv_12s.{T_REC:A}.{WAVELNTH}.{segment}&format=json&protocol=FITS,compress Rice
```

The important keywords are,

* `process`
* `x` (specified by input)
* `y` (specified by input)
* `width` (specified by input)
* `height` (specified by input)
* `locunits`
* `boxunits`

I'm not completely sure about `t`, `r`, or `c`. Presumably one of these controls tracking?

**Comment by davisite** [comment]
@wtbarnes : yup, you got the hang of it; you use the 'process' CGI-URL argument to effect cutouts (and other kinds of reprocessing). I am digging around looking for documentation on each of the processes options - I'm not sure to what degree they are documented.

One thing that is extremely helpful for figuring them out is to go to http://jsoc.stanford.edu/ajax/exportdata.html. Enter a record-set specification, check the `Enable Processing` checkbox, check one or more of the processing-type checkboxes, enter the processing options. Click on the `check parameters` button. If you see "OK to submit export request", THEN check the "check to show export params" checkbox. You will see the `process` parameter value needed to perform the specified processing, like this:

process=n=0|rebin,u=0,scale=0.5,method=boxcar
