### ISSUE TITLE
Allow for alternate communication methods other than HTTP with drms server

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/drms#26]
The drms `Client` assumes that the drms server will be accessed through HTTP by instantiating the `HTTPJsonClient` in the `._json` attribute. However, it may be the case that users want to communicate with the server through some different protocol other than HTTP.

The example I have in mind is a case where netdrms is running locally such that it can be accessed directly (e.g. via show_info, jsoc_info, etc.) on the command line. In this case, drms would need to communicate with the server through a subprocess call.

If this is agreeable, I'm happy to make a PR with this change. I don't *think* it should be too involved. Of course, the default behavior would still be to use `HTTPJsonClient` if the user does not supply some other client.

**Comment by wtbarnes** [comment]
I'm going to close this because I've realized that this can be done easily enough just by subclassing `Client` and making a minor modification to the constructor.

**Comment by kbg** [comment]
I also thought about this, but at KIS we already have the `jsoc_info` and `show_series` CGIs available over HTTP, so it was not really necessary for us. This way we also do not need to set up a database user for everybody who only needs read access to the DRMS: They can just use the `drms` package from Python that does the querying over HTTP and then access the files via NFS.

But feel free to open a PR, if you implement something that runs the required CGIs directly via a subprocess call.

**Comment by wtbarnes** [comment]
I have something implemented, but as I noted above it is quite easy to implement in a subclass as it only required 1 modification to the constructor.

We are working towards making the CGIs available via HTTP soon anyway, so eventually it will just be a matter of adding an additionally ServerConfig and the subclass won't even be needed.
