### ISSUE TITLE
JOSS paper comments

### ISSUE THREAD

**Issue by mgckind** [sunpy/drms#30]
These are comments on the paper itself which is being reviewed [here](https://github.com/openjournals/joss-reviews/issues/1614)

- please add a link to SDO in the intro
- spell out CGI 
> webserver hosting the required CGIs.
- add bold text (not in bold) to the quote below ... and **it is** called a *data series*
> is associated with its own database table and called a data series
- it'd be nice to add snippets used to create Figure 1 (at least the `drms` part)

Review link: openjournals/joss-reviews#1614

**Comment by kbg** [comment]
- I added a reference to SDO: f881ee70e38a71050cc19cf3a26b839c5a98d0c1
- I spelled out CGI and added "it is": b22dfb47a46b2dbbe80097504e1da984e905f5a2
- I added the figure plot script to the examples directory and referred to it in the paper: a77b5c2a162d1d3b23c4cb961f6c94a0ded0723b

I talked to @mbobra about adding code snippets to the paper, and we would both rather try to avoid them. Please let me know if you feel that referring to the plot script does not suffice in this regard.

**Comment by mgckind** [comment]
Yes, I agreed, this is perfect as I looked at the script and a link is just as good. Thanks and congrats!
