### ISSUE TITLE
Add contributions and guidelines for support

### ISSUE THREAD

**Issue by mgckind** [sunpy/drms#31]
Since this is not a subpackage of `sunpy` but an affiliated one, it might need its own explicit instructions for how to contribute to the development or how to report issues and code of conduct. 
Please add a note in this regards so I can check off the Community guidelines checkbox.

Review link: openjournals/joss-reviews#1614

**Comment by mbobra** [comment]
Hello @mgckind, thanks for the review! 

Here are some responses: 

1. The [drms repo](https://github.com/sunpy/drms/community) has already inherited the SunPy Code of Conduct (the yellow dot is a Github bug, but you can look at the Code of Conduct document simply by clicking on it).
2. All the SunPy organization repositories, including drms, are covered by the [SunPy Code of Conduct](https://github.com/sunpy/.github/blob/master/CODE_OF_CONDUCT.md) and the SunPy [contributing document](https://github.com/sunpy/.github/blob/master/CONTRIBUTING.rst). 

Is this enough to satisfy the community guidelines?

**Comment by mgckind** [comment]
Yeah, I think it is. It worth mentioning though in the Readme, as it wasn't clear until now. Thanks

**Comment by kbg** [comment]
I added "Getting Help", "Contributing" and "CoC" sections to the README: b653b70017d579be1bf82b5c4efe10b8d2afa0e3.

**Comment by mgckind** [comment]
I saw it, excellent. Closing issue
