### ISSUE TITLE
Automated or manual steps for test

### ISSUE THREAD

**Issue by mgckind** [sunpy/drms#32]
I can see the test folder for pytest but it'd be useful to add a way to test installation based on those tests, a few lines in the Readme would be enough.  This would be for the Automated test checkbox

Review link: openjournals/joss-reviews#1614

**Comment by kbg** [comment]
I added a section about running tests to the README: 8d7f19bf2627f4d696b35ef80e612ca9575f78c6.

**Comment by mgckind** [comment]
Excellent, closing.
