### ISSUE TITLE
License type not picked by GitHub

### ISSUE THREAD

**Issue by dpshelio** [sunpy/drms#33]
I'm not sure what's the problem with the current format, probably the second line doesn't keep the format as GitHub expects it.

Look at the difference page between [what's now](https://github.com/sunpy/drms/blob/master/LICENSE.txt) and how it was [a while ago](https://github.com/dpshelio/drms/blob/master/LICENSE.txt).

Maybe doing the following change fixes it.

```diff
- Copyright (c) 2014-2019 Kolja Glogowski and others.
- See AUTHORS.txt for a list of contributors.
+ Copyright (c) 2014-2019 Kolja Glogowski and others (see AUTHORS.txt)
```

**Why do I think this is important?** There are a lot of stats collected about open source projects automatically. Though this could be an issue for [Github's licensee](https://github.com/licensee/licensee) software, if they have it, other software likely fails with the same. Making it clearer which license we are using eases the work for people that packages it for distribution or for using it for other software.

**Comment by kbg** [comment]
Thanks for the suggestion. I fixed it in b0d24a859569590e1594cecfd2a08b2aa759a009.
