### ISSUE TITLE
Error while running example create_joss_figure.py

### ISSUE THREAD

**Issue by aureliocarnero** [sunpy/drms#34]
Hello, I had an error while running the create_joss_figure example.

Review link: openjournals/joss-reviews#1614

I have tested all the other examples and none gave any error, so it is only in this example.

After running python create_joss_figure.py, the error is the following:

This example creates the figure shown in the JOSS paper.

Querying metadata...
Finding central meridian crossing...
-> rec_cm: hmi.sharp_720s[4315][2014.07.07_05:12:00_TAI] @ -0.038282 deg
Reading image files...
Creating plots...
Traceback (most recent call last):
  File "create_joss_figure.py", line 147, in <module>
    ax_meta[0].set_xticklabels([])
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py", line 3295, in set_xticklabels
    minor=minor, **kwargs)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axis.py", line 1653, in set_ticklabels
    ticks = self.get_major_ticks()
  File "/usr/lib64/python2.7/site-packages/matplotlib/axis.py", line 1396, in get_major_ticks
    numticks = len(self.get_major_locator()())
  File "/usr/lib64/python2.7/site-packages/matplotlib/dates.py", line 1249, in __call__
    self.refresh()
  File "/usr/lib64/python2.7/site-packages/matplotlib/dates.py", line 1269, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "/usr/lib64/python2.7/site-packages/matplotlib/dates.py", line 1026, in viewlim_to_dt
    .format(vmin))
ValueError: view limit minimum -7.02647999992e+16 is less than 1 and is an invalid Matplotlib date value. This often happens if you pass a non-datetime value to an axis that has datetime units

Do you know if it is something real? Or is it maybe my matplotlib version? This is matplotlib: 2.2.2

Cheers
Aurelio

**Comment by aureliocarnero** [comment]
I have tried with matplotlib version 2.2.3 and I have the same error.

**Comment by kbg** [comment]
Thanks for reporting this issue. It seems be related to the pandas version: I get the same error with "pandas<0.24", but it works fine with "pandas>=0.24" (without changing any other package versions).

I think I have found a workaround for this issue. I'll try to push a fix later.

**Comment by kbg** [comment]
It appears that there is an issue with pandas < v0.24 when using `pandas.Series` containing `pandas.Timestamps` with Matplotlib's `errorbar()` plot.

The following is a minimal example that illustrates this:

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.plotting.register_matplotlib_converters()

t = pd.Series(pd.date_range('2010-01-01', periods=7, freq='AS'))
a = pd.Series(np.sin(np.arange(len(t))))

fig, ax = plt.subplots(nrows=2, num=1, clear=True)
ax[0].plot(t, a)
ax[1].errorbar(t, a, yerr=0.1)
plt.show()
```

This works without problems for "pandas>=0.24", but the `errorbar()` call fails for "pandas<0.24". Curiously, the normal `plot()` call also works for older pandas versions.

To make this work with older pandas versions, one can apparently just use the series values instead, when calling `errorbar()`, i.e.

```python
ax[1].errorbar(t.values, a, yerr=0.1)
```
which I now also used as a workaround for the JOSS plot example.

I could not find any pandas issues that are directly connected to this, but it appears that they have [fixed many datetime-related bugs](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html#datetimelike) in the v0.24 release, so this appears to be resolved in newer versions.

I closed this issue for now, feel free to re-open it, if you still have any problems.

**Comment by aureliocarnero** [comment]
It worked, thanks! Pretty cool code, though. I'm almost finishing with the
validation
