### ISSUE TITLE
Passing a string to segment or key in drms.Client.query fails

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/drms#36]
When passing a string to the `seg` or `key` kwargs in `Client.query`, it splits the string into individual characters rather than interpreting the input as a whole string. Wrapping this in a list fixes this. Presumably, there should be a check to see what the type of these inputs is. If it is a string, wrap it in a list call.

For example, this query

```python
import drms
c = drms.Client()
files = c.query(
    'hmi.ic_720s[2014-01-01T00:00:00_TAI/2d@1d]',
    seg='continuum',
)
```

gives

```python
                c               o               n               t  \
0  InvalidSegName  InvalidSegName  InvalidSegName  InvalidSegName   
1  InvalidSegName  InvalidSegName  InvalidSegName  InvalidSegName   

                i               u               m  
0  InvalidSegName  InvalidSegName  InvalidSegName  
1  InvalidSegName  InvalidSegName  InvalidSegName  

```

**Comment by kbg** [comment]
This is weird. I ran your example with Python 2.7 and Python 3.7 using drms v0.5.7 and I get the following result:

                                     continuum
    0  /SUM98/D516671981/S00003/continuum.fits
    1  /SUM68/D516994153/S00003/continuum.fits

**Comment by kbg** [comment]
I also just tried it with a fresh Python 3.8 environment and still get the correct results.

**Comment by wtbarnes** [comment]
Hi @kbg. I've been using a subclass of `Client` and just realized that this is due to something that I introduced in the subclass. I just confirmed that this works fine using `drms`. Sorry for the noise!
