### ISSUE TITLE
Examples should be formatted as a gallery

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/drms#42]
There are a number of examples in the `examples/` directory but these are not visible in the docs and it isn't entirely clear to me whether these are ever tested or not. Many of them also involve creating figures. These should be reformatted as an example gallery, similar to that in sunpy core.

**Comment by kbg** [comment]
The examples are referenced in the documentation, e.g. [tutorial.html#example-scripts](https://docs.sunpy.org/projects/drms/en/latest/tutorial.html#example-scripts). But I agree that they could be more visible/accessible.

I always ran all examples manually prior making a new release of the `drms` package, so they should still work with the current version of `drms` -- at least if there were no breaking changes in Pandas or other external packages. Maybe this kind of "manual testing" could be automated using `pytest`.

Perhaps it would be a good idea to convert the examples (or a selection of them) into IPython notebooks and add a [Binder](https://mybinder.org/) link to the README. I used IPython notebooks for a [DRMS workshop](https://github.com/kbg/drms-workshop) a few years ago and they work really well in Binder. The advantage of using IPython notebooks and services like Binder is that anybody can directly try out the examples and play around with them without installing anything on their local computer.
