### ISSUE TITLE
Issue with downloading FITS files

### ISSUE THREAD

**Issue by omguptaup** [sunpy/drms#51]
When FITS files are downloaded, the filename is set with the string "HARPNUM" instead of the actual HARP number, as was done in previous versions. The version I am using is 0.6.0.

Current output (version 0.6.0):
-------------------------------------------------------------------------------------------------
Downloading file 1 of 10...
    record: hmi.sharp_cea_720s[5127][2015.02.04_01:00:00_TAI]
  filename: hmi.sharp_cea_720s.HARPNUM.20150204_010000_TAI.magnetogram.fits
-------------------------------------------------------------------------------------------------

Old output (previous versions):
-------------------------------------------------------------------------------------------------
Downloading file 1 of 10...
    record: hmi.sharp_cea_720s[5127][2015.02.04_01:00:00_TAI]
  filename: hmi.sharp_cea_720s.5127.20150204_010000_TAI.magnetogram.fits
-------------------------------------------------------------------------------------------------

**Comment by nabobalis** [comment]
Yeah it seems that some keywords are not being substituted. I will investigate.

**Comment by dstansby** [comment]
Just ran into this - in case it's helpful for others, the issue is present in version 0.6.0, but not the previous version 0.5.7.
