### ISSUE TITLE
DRMS Exportdata intermittently gives an error when using the cutout service

### ISSUE THREAD

**Issue by mbobra** [sunpy/drms#56]
### Description

JSOC Exportdata intermittently gives an error when using the cutout service. Often, the error looks like this:

`DrmsExportError: Cant save new export-request hash. [status=4]` 

However, this is not reproducible. 

This is not a problem in the `drms` package, but rather a bug in JSOC Exportdata. I'm creating this issue here to keep track of this error so that we can resolve the problems it is causing in our test suite.

cc @davisite

**Comment by wtbarnes** [comment]
I'm going to close this as the cutout example does not seem to be failing the sunpy test suite consistently any more. We can reopen this if this exception consistently starts popping up again.
